version: '2'
services: 
    adoptie-mysql:
        build:
            context: .
            dockerfile: ./Dockerfile.mariadb
        volumes: 
            - adoptie-mysqldb:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWD:-rood}
            MYSQL_DATABASE: "cmdi_forms"
        networks:
            - adoptie-network 

    # huc-editor backend & frontend
    adoptie-php-apache:
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - 8130:80
        volumes:
            - /backup/data:/backup/data
            - /data/iisg-adoptie/records/:/var/www/html/ccf/data/records/
            - /data/iisg-adoptie/resources/:/var/www/html/ccf/data/resources/
            - /data/iisg-adoptie/htp:/var/www/htp
            - /data/iisg-adoptie/.htaccess:/var/www/html/.htaccess
            #- ./data/records/:/var/www/html/ccf/data/records/
            #- ./data/resources/:/var/www/html/ccf/data/resources/
            #- ./data/.htaccess:/var/www/html/.htaccess
            #- ./data/htp:/var/www/htp
        environment:
            TITLE: "IISG Adoptie Editor"
            PROFILE: "Adoptie"
            SUBTITLE: ""
            BASE_URL: "https://adoptie.sd.di.huc.knaw.nl/ccf/"
            #BASE_URL: "http://0.0.0.0:8130/ccf/"
            TZ: "Europe/Amsterdam"
            DB_SERVER: adoptie-mysql
            DB_USER: root
            DB_PASSWD: ${DB_PASSWD:-rood}
            DB_NAME: cmdi_forms
        labels:
        - "traefik.enable=true"
        - "traefik.http.routers.adoptie.entrypoints=http"
        - "traefik.http.routers.adoptie.rule=Host(`adoptie.sd.di.huc.knaw.nl`)"
        networks:
            - adoptie-network
        depends_on:
            - adoptie-mysql
    adoptie-backup:
        build:
            context: .
            dockerfile: ./Dockerfile.backup
        restart: unless-stopped
        environment:
            BACKUP_HOUR: "01"
            BACKUP_MINUTE: "25"
            BACKUP_NAME: "iisg-adoptie"
            BACKUP_LOCATION: "/backup/data"
            BACKUP_FILE: "$BACKUP_LOCATION/$BACKUP_NAME.tgz"
            DB_SERVER: adoptie-mysql
            DB_USER: root
            DB_PASSWD: ${DB_PASSWD:-rood}
            DB_NAME: cmdi_forms
        volumes:
            - /backup/data:/backup/data
            - /data/iisg-adoptie/records/:/data/records/
            - /data/iisg-adoptie/resources/:/data/resources/
            - /data/iisg-adoptie/htp:/data/htp
            - /data/iisg-adoptie/.htaccess:/data/.htaccess
            #- ./data/backup:/backup/data
            #- ./data/records/:/data/records/
            #- ./data/resources/:/data/resources/
            #- ./data/.htaccess:/data/.htaccess
            #- ./data/htp:/data/htp
        networks:
            - adoptie-network
        depends_on:
            - adoptie-mysql
networks:
  adoptie-network:
    external: true
    name: traefik-public
volumes:
    adoptie-mysqldb:
