version: '2'
services: 
    niod-yugo-mysql:
        build:
            context: .
            dockerfile: ./Dockerfile.mariadb
        volumes: 
            - niod-yugo-mysqldb:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWD:-rood}
            MYSQL_DATABASE: "cmdi_forms"
        networks:
            - niod-yugo-network 

    # huc-editor backend & frontend
    niod-yugo-php-apache:
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - 8136:80
        volumes:
            - /backup/data:/backup/data
            - /data/niod-yugo/records/:/var/www/html/ccf/data/records/
            - /data/niod-yugo/resources/:/var/www/html/ccf/data/resources/
            - /data/niod-yugo/htp:/var/www/htp
            - /data/niod-yugo/.htaccess:/var/www/html/.htaccess
            #- ./data/records/:/var/www/html/ccf/data/records/
            #- ./data/resources/:/var/www/html/ccf/data/resources/
            #- ./data/.htaccess:/var/www/html/.htaccess
            #- ./data/htp:/var/www/htp
        environment:
            TITLE: "NIOD Yugoslavia Editor"
            PROFILE: "CollectionHolder"
            SUBTITLE: "Collection Holder"
            BASE_URL: "https://yugoslavia.sd.dev.huc.knaw.nl/ccf/"
            #BASE_URL: "http://0.0.0.0:8136/ccf/"
            TZ: "Europe/Amsterdam"
            DB_SERVER: niod-yugo-mysql
            DB_USER: root
            DB_PASSWD: ${DB_PASSWD:-rood}
            DB_NAME: cmdi_forms
        labels:
        - "traefik.enable=true"
        - "traefik.http.routers.niod-yugo.entrypoints=http"
        - "traefik.http.routers.niod-yugo.rule=Host(`yugoslavia.sd.huc.knaw.nl`)"
        networks:
            - niod-yugo-network
        depends_on:
            - niod-yugo-mysql
networks:
  niod-yugo-network:
    external: true
    name: traefik-public
volumes:
    niod-yugo-mysqldb:
