version: '2'
services: 
    adoptie-mysql:
        build:
            context: .
            dockerfile: ./Dockerfile.mariadb
        volumes: 
            - adoptie-mysqldb:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWD:-rood}
            MYSQL_DATABASE: "cmdi_forms"
        networks:
            - adoptie-network 

    # huc-editor backend & frontend
    adoptie-php-apache:
        build:
            context: .
            dockerfile: ./Dockerfile
            no-cache: true
        ports:
            - 8130:80
        volumes:
            - ./data/records/:/var/www/html/ccf/data/records/
            - ./data/resources/:/var/www/html/ccf/data/resources/
        environment:
            TITLE: "IISG Adoptie Editor"
            PROFILE: "Adoptie"
            SUBTITLE: ""
            BASE_URL: "https://adoptie.sd.di.huc.knaw.nl/ccf/"
#            BASE_URL: "http://0.0.0.0:8130/ccf/"
            TZ: "Europe/Amsterdam"
            DB_SERVER: adoptie-mysql
            DB_USER: root
            DB_PASSWD: ${DB_PASSWD:-rood}
            DB_NAME: cmdi_forms
        labels:
        - "traefik.enable=true"
        - "traefik.http.routers.adoptie.entrypoints=http"
        - "traefik.http.routers.adoptie.rule=Host(`adoptie.sd.di.huc.knaw.nl`)"
        networks:
            - adoptie-network
        depends_on:
            - adoptie-mysql
networks:
  adoptie-network:
    external: true #false
    name: traefik-public
volumes:
    adoptie-mysqldb:
