version: '2'
services: 
    hi-de-mysql:
        build:
            context: .
            dockerfile: ./Dockerfile.mariadb
        volumes: 
            - hi-de-mysqldb:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWD:-rood}
            MYSQL_DATABASE: "cmdi_forms"
        networks:
            - hi-de-network 

    # huc-editor backend & frontend
    hi-de-php-apache:
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - 8125:80
        volumes:
            - /data/hide/records/:/var/www/html/ccf/data/records/
            - /data/hide/resources/:/var/www/html/ccf/data/resources/
        environment:
            TITLE: "HI Data Envelope Editor"
            PROFILE: "DataEnvelope"
            SUBTITLE: "your way to a FAIR dataset"
            BASE_URL: "https://hide.sd.di.huc.knaw.nl/ccf/"
#            BASE_URL: "http://0.0.0.0:8125/ccf/"
            TZ: "Europe/Amsterdam"
            DB_SERVER: hi-de-mysql
            DB_USER: root
            DB_PASSWD: ${DB_PASSWD:-rood}
            DB_NAME: cmdi_forms
        labels:
        - "traefik.enable=true"
        - "traefik.http.routers.hide.entrypoints=http"
        - "traefik.http.routers.hide.rule=Host(`hide.sd.di.huc.knaw.nl`)"
        networks:
            - hi-de-network
        depends_on:
            - hi-de-mysql
networks:
  hi-de-network:
    external: true 
    name: traefik-public
volumes:
    hi-de-mysqldb:
