version: '2'
services: 
    niod-yugo-mysql:
        build:
            context: .
            dockerfile: ./Dockerfile.mariadb
        volumes: 
            - niod-yugo-mysqldb:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWD:-rood}
            MYSQL_DATABASE: "cmdi_forms"
        networks:
            - niod-yugo-network 

    # huc-editor backend & frontend
    niod-yugo-php-apache:
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - 8136:80
        volumes:
            - /data/products/niod-yugo/records/:/var/www/html/ccf/data/records/
            - /data/products/niod-yugo/resources/:/var/www/html/ccf/data/resources/
            - /data/products/niod-yugo/htp:/var/www/htp
            - /data/products/niod-yugo/.htaccess:/var/www/html/.htaccess
            #- ./data/records/:/var/www/html/ccf/data/records/
            #- ./data/resources/:/var/www/html/ccf/data/resources/
            #- ./data/.htaccess:/var/www/html/.htaccess
            #- ./data/htp:/var/www/htp
        environment:
            TITLE: "NIOD Yugoslavia Editor"
            PROFILE: "CollectionHolder"
            SUBTITLE: "Collection Holder"
            BASE_URL: "https://yugoslavia.sd.di.huc.knaw.nl/ccf/"
            #BASE_URL: "http://0.0.0.0:8136/ccf/"
            TZ: "Europe/Amsterdam"
            DB_SERVER: niod-yugo-mysql
            DB_USER: root
            DB_PASSWD: ${DB_PASSWD:-rood}
            DB_NAME: cmdi_forms
        labels:
        - "traefik.enable=true"
        - "traefik.http.routers.niod-yugo.entrypoints=http"
        - "traefik.http.routers.niod-yugo.rule=Host(`yugoslavia.sd.di.huc.knaw.nl`)"
        networks:
            - niod-yugo-network
        depends_on:
            - niod-yugo-mysql
    niod-yugo-backup:
        build:
            context: .
            dockerfile: ./Dockerfile.backup
        restart: unless-stopped
        environment:
            BACKUP_HOUR: "01"
            BACKUP_MINUTE: "35"
            BACKUP_NAME: "niod-yugo"
            BACKUP_LOCATION: "/backup/data"
            BACKUP_FILE: "$BACKUP_LOCATION/$BACKUP_NAME.tgz"
            DB_SERVER: niod-yugo-mysql
            DB_USER: root
            DB_PASSWD: ${DB_PASSWD:-rood}
            DB_NAME: cmdi_forms
        volumes:
            - /backup/data/:/backup/data # in prod change to /backup/data:/backup/data
            - /data/products/niod-yugo/records/:/data/records/
            - /data/products/niod-yugo/resources/:/data/resources/
            - /data/products/niod-yugo/htp:/data/htp
            - /data/products/niod-yugo/.htaccess:/data/.htaccess
            #- ./data/backup:/backup/data
            #- ./data/records/:/data/records/
            #- ./data/resources/:/data/resources/
            #- ./data/.htaccess:/data/.htaccess
            #- ./data/htp:/data/htp
        networks:
            - niod-yugo-network
        depends_on:
            - niod-yugo-mysql
networks:
  niod-yugo-network:
    external: true
    name: traefik-public
volumes:
    niod-yugo-mysqldb:
